/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class TelaInicio extends javax.swing.JFrame {
    // Declaração de variáveis
    private final String cargo;

    /**
     * Creates new form Inicio
     */
    public TelaInicio(String _cargo) {
        this.cargo = _cargo;
        initComponents();
        setLocationRelativeTo(null);
        verificarPermissoes();
    }
    
    // Método para verificar quais telas o usuário pode acessar
    public void verificarPermissoes() {
        switch(cargo) {
            case "Padeiro":
                btnRelatorios.setEnabled(true);
                btnPromocoes.setEnabled(false);
                btnCadastroFuncionarios.setEnabled(false);
                btnProdutos.setEnabled(true);
                btnInsumos.setEnabled(true);
                btnFidelidade.setEnabled(false);
                btnReceitas.setEnabled(true);
                btnControleCaixa.setEnabled(false);
                break;
            case "Gestor financeiro":
                btnRelatorios.setEnabled(true);
                btnPromocoes.setEnabled(true);
                btnCadastroFuncionarios.setEnabled(false);
                btnProdutos.setEnabled(true);
                btnInsumos.setEnabled(true);
                btnFidelidade.setEnabled(false);
                btnReceitas.setEnabled(false);
                btnControleCaixa.setEnabled(true);
                break;
            case "Caixa":
                btnRelatorios.setEnabled(true);
                btnPromocoes.setEnabled(true);
                btnCadastroFuncionarios.setEnabled(false);
                btnProdutos.setEnabled(true);
                btnInsumos.setEnabled(false);
                btnFidelidade.setEnabled(true);
                btnReceitas.setEnabled(false);
                btnControleCaixa.setEnabled(true);
                break;
            case "Gerente":
                btnRelatorios.setEnabled(true);
                btnPromocoes.setEnabled(true);
                btnCadastroFuncionarios.setEnabled(true);
                btnProdutos.setEnabled(true);
                btnInsumos.setEnabled(true);
                btnFidelidade.setEnabled(true);
                btnReceitas.setEnabled(true);
                btnControleCaixa.setEnabled(true);
                break;
            case "Programador":
                btnRelatorios.setEnabled(true);
                btnPromocoes.setEnabled(true);
                btnCadastroFuncionarios.setEnabled(true);
                btnProdutos.setEnabled(true);
                btnInsumos.setEnabled(true);
                btnFidelidade.setEnabled(true);
                btnReceitas.setEnabled(true);
                btnControleCaixa.setEnabled(true);
                break;
            default:
                btnRelatorios.setEnabled(false);
                btnPromocoes.setEnabled(false);
                btnCadastroFuncionarios.setEnabled(false);
                btnProdutos.setEnabled(false);
                btnInsumos.setEnabled(false);
                btnFidelidade.setEnabled(false);
                btnReceitas.setEnabled(false);
                btnControleCaixa.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRelatorios = new javax.swing.JButton();
        btnPromocoes = new javax.swing.JButton();
        btnCadastroFuncionarios = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        btnFidelidade = new javax.swing.JButton();
        btnReceitas = new javax.swing.JButton();
        btnControleCaixa = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInicio.setText("INÍCIO");

        btnRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnPromocoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPromocoes.setText("Promoções");
        btnPromocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocoesActionPerformed(evt);
            }
        });

        btnCadastroFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroFuncionarios.setText("Cadastro funcionários");
        btnCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFuncionariosActionPerformed(evt);
            }
        });

        btnProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProdutos.setText("Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnInsumos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsumos.setText("Insumos");
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });

        btnFidelidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFidelidade.setText("Fidelidade");
        btnFidelidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFidelidadeActionPerformed(evt);
            }
        });

        btnReceitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReceitas.setText("Receitas");
        btnReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceitasActionPerformed(evt);
            }
        });

        btnControleCaixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnControleCaixa.setText("Controle caixa");
        btnControleCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleCaixaActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFidelidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnControleCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInicio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPromocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInicio)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorios)
                    .addComponent(btnPromocoes)
                    .addComponent(btnCadastroFuncionarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutos)
                    .addComponent(btnInsumos)
                    .addComponent(btnFidelidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceitas)
                    .addComponent(btnControleCaixa)
                    .addComponent(btnSair))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Sair do programa
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
                null, // Componente pai (null para centro da tela)
                "Deseja realmente sair?", // Mensagem
                "Confirmação", // Título da janela
                JOptionPane.YES_NO_OPTION // Tipo de opções
        );

        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    // Abre a tela de relatórios se tiver tal permissão
    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        TelaRelatorio telaRelatorio = new TelaRelatorio();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    // Abre a tela de produtos se tiver tal permissão
    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        TelaProdutos telaProdutos = new TelaProdutos();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    // Abre a tela de fidelidade se tiver tal permissão
    private void btnFidelidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFidelidadeActionPerformed
        TelaFidelidade telaFidelidade = new TelaFidelidade();
        telaFidelidade.setVisible(true);
    }//GEN-LAST:event_btnFidelidadeActionPerformed

    // Abre a tela de insumos se tiver tal permissão
    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        TelaInsumos telaInsumos = new TelaInsumos();
        telaInsumos.setVisible(true);
    }//GEN-LAST:event_btnInsumosActionPerformed

    // Abre a tela de receitas se tiver tal permissão
    private void btnReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceitasActionPerformed
        TelaReceitas telaReceitas = new TelaReceitas();
        telaReceitas.setVisible(true);
    }//GEN-LAST:event_btnReceitasActionPerformed

    // Abre a tela de promoções se tiver tal permissão
    private void btnPromocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocoesActionPerformed
        TelaPromocoes telaPromocoes = new TelaPromocoes();
        telaPromocoes.setVisible(true);
    }//GEN-LAST:event_btnPromocoesActionPerformed

    // Abre a tela de cadastro de usuários se tiver tal permissão
    private void btnCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFuncionariosActionPerformed
        TelaCadastroUsuario telaCadastroUsuario = new TelaCadastroUsuario();
        telaCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_btnCadastroFuncionariosActionPerformed

    private void btnControleCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleCaixaActionPerformed
        TelaControleCaixa telaControleCaixa = new TelaControleCaixa();
        telaControleCaixa.setVisible(true);
    }//GEN-LAST:event_btnControleCaixaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroFuncionarios;
    private javax.swing.JButton btnControleCaixa;
    private javax.swing.JButton btnFidelidade;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnPromocoes;
    private javax.swing.JButton btnReceitas;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblInicio;
    // End of variables declaration//GEN-END:variables
}
